load('iIT341_modified.mat');
%% modified Recon 3D model
load('model_final.mat');
old={'ficytcc553[c]'
'focytcc553[c]'
'dhnpt[c]'
'ala__D[c]'
'ala__D[e]'
'ala__L[c]'
'ala__L[e]'
'arg__L[c]'
'arg__L[e]'
'asn__L[c]'
'asn__L[e]'
'asp__L[c]'
'asp__L[e]'
'citr__L[c]'
'cys__L[c]'
'cys__L[e]'
'cyst__L[c]'
'dhor__S[c]'
'glc__D[c]'
'glc__D[e]'
'gln__L[c]'
'gln__L[e]'
'glu__D[c]'
'glu__L[c]'
'glu__L[e]'
'hcys__L[c]'
'his__L[c]'
'his__L[e]'
'hom__L[c]'
'ile__L[c]'
'ile__L[e]'
'lac__D[c]'
'lac__L[c]'
'lac__L[e]'
'lald__L[c]'
'leu__L[c]'
'leu__L[e]'
'lys__L[c]'
'lys__L[e]'
'mal__L[c]'
'mal__L[e]'
'met__L[c]'
'met__L[e]'
'pant__R[c]'
'phe__L[c]'
'phe__L[e]'
'pnto__R[c]'
'pro__L[c]'
'pro__L[e]'
'pser__D[c]'
'pser__L[c]'
'rib__D[c]'
'ru5p__D[c]'
'ser__D[c]'
'ser__D[e]'
'ser__L[c]'
'ser__L[e]'
'thr__L[c]'
'thr__L[e]'
'trp__L[c]'
'trp__L[e]'
'tyr__L[c]'
'tyr__L[e]'
'val__L[c]'
'val__L[e]'
'xu5p__D[c]'};
new={'ficytC[c]'
'focytC[c]'
'HC01361[c]'
'ala_D[c]'
'ala_D[e]'
'ala_L[c]'
'ala_L[e]'
'arg_L[c]'
'arg_L[e]'
'asn_L[c]'
'asn_L[e]'
'asp_L[c]'
'asp_L[e]'
'citr_L[c]'
'cys_L[c]'
'cys_L[e]'
'cyst_L[c]'
'dhor_S[c]'
'glc_D[c]'
'glc_D[e]'
'gln_L[c]'
'gln_L[e]'
'glu_D[c]'
'glu_L[c]'
'glu_L[e]'
'hcys_L[c]'
'his_L[c]'
'his_L[e]'
'hom_L[c]'
'ile_L[c]'
'ile_L[e]'
'lac_D[c]'
'lac_L[c]'
'lac_L[e]'
'lald_L[c]'
'leu_L[c]'
'leu_L[e]'
'lys_L[c]'
'lys_L[e]'
'mal_L[c]'
'mal_L[e]'
'met_L[c]'
'met_L[e]'
'pant_R[c]'
'phe_L[c]'
'phe_L[e]'
'pnto_R[c]'
'pro_L[c]'
'pro_L[e]'
'pser_D[c]'
'pser_L[c]'
'rib_D[c]'
'ru5p_D[c]'
'ser_D[c]'
'ser_D[e]'
'ser_L[c]'
'ser_L[e]'
'thr_L[c]'
'thr_L[e]'
'trp_L[c]'
'trp_L[e]'
'tyr_L[c]'
'tyr_L[e]'
'val_L[c]'
'val_L[e]'
'xu5p_D[c]'};

%% update the nomenclature to match with Recon 3D
findMetIDs(iIT341,old);
iIT341.mets(ans)=new;
fba=optimizeCbModel(iIT341)

%% identify reactions that are TICs and modify them accordingly
[rxnInLoopfinal, Nfinal, loopInfofinal] = findMinNull(iIT341);
find(rxnInLoopfinal(:,1)==1);
backward1a=iIT341.rxns(ans);
find(rxnInLoopfinal(:,2)==1);
forward1a=iIT341.rxns(ans);
both1a=intersect(forward1a,backward1a);
%%
block={'HCO3E'
'HCYSHSL'
'NAt3_1'};
blockid = findRxnIDs(iIT341,block);
iIT341.lb(blockid)=0;
iIT341.ub(blockid)=0;
fba1=optimizeCbModel(iIT341)
%%
[rxnInLoopfinal, Nfinal, loopInfofinal] = findMinNull(iIT341);
find(rxnInLoopfinal(:,1)==1);
backward1a=iIT341.rxns(ans);
find(rxnInLoopfinal(:,2)==1);
forward1a=iIT341.rxns(ans);
both1a=intersect(forward1a,backward1a);
%%
blockid = findRxnIDs(iIT341,backward1a(1:2));
iIT341.lb(blockid)=0;
fba2=optimizeCbModel(iIT341)
%%
findRxnIDs(iIT341,{'HPROx'});
iIT341.ub(ans)=0;
fba3=optimizeCbModel(iIT341)
%%
findRxnIDs(iIT341,{'AHSERL2'});
iIT341.lb(ans)=0;
iIT341.ub(ans)=0;
fba4=optimizeCbModel(iIT341)